[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "melp"
authors = [
    {name = "Fuying Wang", email = "fuyingw@connect.hku.hk"},
    {name = "Jiacheng Xu"},
]
description = "From Token to Rhythm: A Multi-Scale Approach for ECG-Language Pretraining"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.10"
# TODO: update dependencies later
dependencies = [
    "pandas",
    "torch",
    "lightning"
]

[tool.setuptools.packages.find]
where = ["src"]    # list of folders that contain the packages (["."] by default)
include = ["melp*"]  # package names, not folders: src/melp -> "melp", "melp.models", ...
exclude = []         # exclude packages matching these glob patterns (empty by default)
namespaces = false   # to disable scanning PEP 420 namespaces (true by default)
